#!/usr/bin/env python3
"""Regenerate LinkML-derived ontology artifacts.

This script is the single deterministic bridge between
``app/ontology/startup_ontology.linkml.yaml`` (the source of truth) and the
runtime artifacts living in ``app/ontology/generated/``:

* ``models.py``              -- Pydantic v2 classes
* ``schema.json``            -- JSON-Schema
* ``shapes.ttl``             -- SHACL shapes (Turtle)
* ``cypher_constraints.cypher`` -- Neo4j DDL (constraints + indexes)

The Cypher generator is bespoke -- it walks the LinkML SchemaView, picks up
slots annotated with ``relation: true``, and emits per-class constraints +
per-relationship indexes that match exactly what ``Neo4jService.ensure_schema``
emitted before Phase 1.

Run via ``make generate`` or directly:

    python scripts/generate_ontology_artifacts.py

Use ``--check`` to write into a temp directory and diff against the committed
artifacts.  This is the basis of the CI drift check.
"""

from __future__ import annotations

import argparse
import difflib
import filecmp
import os
import shutil
import sys
import tempfile
from pathlib import Path


# Determinism: rdflib's canonicalization and several LinkML internals iterate
# Python dicts and sets; without a fixed hash seed those iterations vary
# between processes and produce noise in the generated artifacts.  Re-exec
# ourselves once with PYTHONHASHSEED=0 to guarantee byte-stable output.
if os.environ.get("PYTHONHASHSEED") != "0" and not os.environ.get(
    "_FG_GENERATOR_REEXEC"
):
    os.environ["PYTHONHASHSEED"] = "0"
    os.environ["_FG_GENERATOR_REEXEC"] = "1"
    os.execvpe(sys.executable, [sys.executable, *sys.argv], os.environ)

# Header line stamped onto every generated artifact so reviewers can spot
# hand-edits.  Cypher uses ``--`` and Python/JSON/TTL use ``#``; the runner
# below picks the right comment marker per file extension.
HEADER_TEXT = "Generated by scripts/generate_ontology_artifacts.py -- DO NOT EDIT"

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = PROJECT_ROOT / "app" / "ontology" / "startup_ontology.linkml.yaml"
DEFAULT_OUTDIR = PROJECT_ROOT / "app" / "ontology" / "generated"


def _comment_prefix(suffix: str) -> str:
    """Return the comment marker for a given file suffix."""
    if suffix == ".cypher":
        return "// "
    if suffix == ".json":
        # JSON-Schema does not support comments natively.  We keep the header
        # as a metadata key inside the JSON document instead (see below).
        return ""
    return "# "


def _is_relation_slot(slot) -> bool:
    """Detect slots flagged as Neo4j relationship predicates.

    A slot is a relationship predicate when its ``relation`` annotation is
    truthy.  We accept the string ``"true"`` and the boolean ``True`` so that
    YAML parsers in either mode produce the same result.
    """
    if not getattr(slot, "annotations", None):
        return False
    ann = slot.annotations.get("relation")
    if ann is None:
        return False
    value = getattr(ann, "value", ann)
    return str(value).lower() == "true"


def _relation_predicate(slot) -> str | None:
    """Return the explicit Neo4j predicate name annotated on a slot."""
    if not getattr(slot, "annotations", None):
        return None
    ann = slot.annotations.get("predicate")
    if ann is None:
        return None
    value = getattr(ann, "value", ann)
    return str(value) if value else None


# ---------------------------------------------------------------------------
# Individual generators
# ---------------------------------------------------------------------------

def generate_pydantic(schema_path: Path, out_path: Path) -> None:
    from linkml.generators.pydanticgen import PydanticGenerator

    gen = PydanticGenerator(str(schema_path))
    body = gen.serialize()
    header = f"# {HEADER_TEXT}\n# Source: {schema_path.name}\n"
    out_path.write_text(header + body, encoding="utf-8")


def generate_jsonschema(schema_path: Path, out_path: Path) -> None:
    """Emit JSON-Schema plus FounderGraph-specific relation metadata.

    The upstream JSON-Schema only describes the property bag of each entity
    class -- relation slots (predicates with domain + range) are dropped.  We
    re-attach them under ``x-foundergraph-relations`` so the runtime
    ``OntologyLoader`` can reconstruct allowed_relationships and the
    domain/range map without re-reading the LinkML YAML.
    """
    import json

    from linkml.generators.jsonschemagen import JsonSchemaGenerator
    from linkml_runtime.utils.schemaview import SchemaView

    gen = JsonSchemaGenerator(str(schema_path))
    raw = gen.serialize()
    payload = json.loads(raw)
    payload["$comment"] = HEADER_TEXT
    payload["x-foundergraph-source"] = schema_path.name

    sv = SchemaView(str(schema_path))
    relations: list[dict[str, str]] = []
    for slot_name in sorted(sv.all_slots().keys()):
        slot = sv.get_slot(slot_name)
        if not _is_relation_slot(slot):
            continue
        predicate = _relation_predicate(slot)
        if not predicate:
            continue
        relations.append(
            {
                "slot": slot_name,
                "predicate": predicate,
                "domain": str(slot.domain or ""),
                "range": str(slot.range or ""),
            }
        )
    payload["x-foundergraph-relations"] = relations

    # Track which classes inherit from the Entity mixin so the runtime knows
    # which JSON-Schema $defs to surface as allowed node labels.
    entity_labels: list[str] = []
    for cls_name in sorted(sv.all_classes().keys()):
        ancestors = sv.class_ancestors(cls_name)
        if "Entity" in ancestors and cls_name not in {"Entity"}:
            entity_labels.append(cls_name)
    payload["x-foundergraph-entity-labels"] = entity_labels

    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    out_path.write_text(text, encoding="utf-8")


def generate_shacl(schema_path: Path, out_path: Path) -> None:
    """Emit SHACL shapes for the LinkML schema.

    The upstream ShaclGenerator emits blank-node properties in
    iteration-dependent order, which produces a fresh ``shapes.ttl`` on every
    run and breaks the drift check.  We normalize by round-tripping through
    rdflib's NT serializer (sorted triples) so the output is canonical and
    diff-friendly across runs.
    """
    import rdflib
    from rdflib.compare import to_canonical_graph

    from linkml.generators.shaclgen import ShaclGenerator

    gen = ShaclGenerator(str(schema_path))
    body = gen.serialize()
    graph = rdflib.Graph()
    graph.parse(data=body, format="turtle")
    # ``to_canonical_graph`` re-labels blank nodes deterministically based on
    # triple hashes; sorting the resulting N-Triples lines yields a canonical
    # textual form so subsequent runs produce byte-identical output.
    canonical = to_canonical_graph(graph)
    nt_lines = sorted(canonical.serialize(format="nt").splitlines())
    header = f"# {HEADER_TEXT}\n# Source: {schema_path.name}\n"
    out_path.write_text(
        header + "\n".join(line for line in nt_lines if line) + "\n",
        encoding="utf-8",
    )


def generate_cypher(schema_path: Path, out_path: Path) -> None:
    """Emit the Cypher DDL bundle (constraints + per-rel indexes).

    The output is what ``Neo4jService.ensure_schema`` used to compute inline
    in Phase 0 -- now it's a generated artifact loaded at runtime so the
    schema-of-record is one file instead of two implementations that can drift.
    """
    from linkml_runtime.utils.schemaview import SchemaView

    # Phase 4: read the embedding dimensionality from the central config so the
    # generated vector index DDL stays in lock-step with the Ollama embed model.
    # Neo4j refuses to accept ``vector.dimensions`` as a parameter, so we MUST
    # bake the integer into the DDL text -- which is why the generator owns it.
    try:
        from app.config import EMBEDDING_DIMS
    except Exception:  # pragma: no cover -- defensive when running outside the venv
        EMBEDDING_DIMS = 768

    sv = SchemaView(str(schema_path))

    lines: list[str] = []
    lines.append(f"// {HEADER_TEXT}")
    lines.append(f"// Source: {schema_path.name}")
    lines.append("// Apply via Neo4jService.ensure_schema().")
    lines.append("")

    # 1. Constraints -- one CREATE CONSTRAINT per class with an ``id`` slot.
    lines.append("// --- Uniqueness constraints (entity id, document id) ---")
    lines.append(
        "CREATE CONSTRAINT document_id IF NOT EXISTS FOR (d:Document) REQUIRE d.id IS UNIQUE;"
    )
    lines.append(
        "CREATE CONSTRAINT entity_id IF NOT EXISTS FOR (e:Entity) REQUIRE e.id IS UNIQUE;"
    )
    # Per-subclass id constraint for Startup -- legacy behavior preserved.
    if "Startup" in sv.all_classes():
        lines.append(
            "CREATE CONSTRAINT startup_id IF NOT EXISTS FOR (s:Startup) REQUIRE s.id IS UNIQUE;"
        )

    # 2. Entity-level lookup indexes that ensure_schema previously hardcoded.
    lines.append("")
    lines.append("// --- Entity lookup indexes ---")
    lines.append(
        "CREATE INDEX entity_type IF NOT EXISTS FOR (e:Entity) ON (e.type);"
    )
    lines.append(
        "CREATE INDEX entity_validation_status IF NOT EXISTS FOR (e:Entity) "
        "ON (e.validation_status);"
    )
    lines.append(
        "CREATE INDEX entity_source_document_id IF NOT EXISTS FOR (e:Entity) "
        "ON (e.source_document_id);"
    )

    # 3. Per-relationship indexes -- one per ontology-declared predicate.
    rel_names: list[str] = []
    for slot_name in sorted(sv.all_slots().keys()):
        slot = sv.get_slot(slot_name)
        if not _is_relation_slot(slot):
            continue
        pred = _relation_predicate(slot)
        if not pred:
            continue
        rel_names.append(pred)

    # Also include common relation types the ontology validator treats as
    # always-allowed (utility predicates) even when they're not in the LinkML
    # graph.  Keeping these in the DDL preserves Phase 0 behavior 1:1.
    for utility in ("MENTIONS", "SOURCE_OF", "RELATED_TO", "SUPERSEDED_BY"):
        if utility not in rel_names:
            rel_names.append(utility)

    lines.append("")
    lines.append("// --- Per-relationship id indexes (one per allowed predicate) ---")
    for rel in sorted(set(rel_names)):
        lines.append(
            f"CREATE INDEX rel_{rel}_id IF NOT EXISTS FOR ()-[r:`{rel}`]-() ON (r.id);"
        )

    # 4. Phase 4: native Neo4j vector index for entity-summary embeddings.
    # Chunk vectors stay in Qdrant; this index covers the entity tier only.
    # ``vector.dimensions`` is hardcoded because Neo4j does not accept it as a
    # parameter on index creation; if the embedding model changes, bump
    # ``EMBEDDING_DIMS`` in ``app/config.py`` and re-run ``make generate``.
    # Older Neo4j servers (<5.11) lack vector indexes -- ``ensure_schema``
    # tolerates the resulting failure with a logged warning so the rest of
    # the schema still applies.
    lines.append("")
    lines.append("// --- Native vector indexes (Phase 4 / Phase 7) ---")
    dims = int(EMBEDDING_DIMS)
    lines.append(
        "CREATE VECTOR INDEX entity_embedding IF NOT EXISTS FOR (e:Entity) ON e.embedding "
        "OPTIONS {indexConfig: {`vector.dimensions`: "
        + str(dims)
        + ", `vector.similarity_function`: 'cosine'}};"
    )
    # Phase 7 stub -- community summaries are not yet materialised, so we keep
    # the DDL commented out.  Uncomment (and re-run ``make generate``) once
    # ``app/services/community_service.py`` is in place.
    lines.append(
        "// CREATE VECTOR INDEX community_embedding IF NOT EXISTS FOR (c:Community) ON c.embedding "
        "OPTIONS {indexConfig: {`vector.dimensions`: "
        + str(dims)
        + ", `vector.similarity_function`: 'cosine'}};"
    )

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def regenerate(schema_path: Path, out_dir: Path) -> dict[str, Path]:
    """Regenerate all artifacts into ``out_dir`` and return their paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    artifacts = {
        "models.py": out_dir / "models.py",
        "schema.json": out_dir / "schema.json",
        "shapes.ttl": out_dir / "shapes.ttl",
        "cypher_constraints.cypher": out_dir / "cypher_constraints.cypher",
    }
    generate_pydantic(schema_path, artifacts["models.py"])
    generate_jsonschema(schema_path, artifacts["schema.json"])
    generate_shacl(schema_path, artifacts["shapes.ttl"])
    generate_cypher(schema_path, artifacts["cypher_constraints.cypher"])

    # Drop an __init__.py so ``app.ontology.generated`` is a proper package.
    init_path = out_dir / "__init__.py"
    init_text = (
        f"# {HEADER_TEXT}\n"
        '"""Generated LinkML artifacts (see scripts/generate_ontology_artifacts.py)."""\n'
    )
    init_path.write_text(init_text, encoding="utf-8")
    artifacts["__init__.py"] = init_path
    return artifacts


def diff_dirs(left: Path, right: Path) -> list[str]:
    """Return a unified-diff-flavored list of mismatching file names.

    Returns an empty list when the two directories are equivalent (same files,
    same contents).  This is the basis of the ``--check`` drift gate.
    """
    diffs: list[str] = []
    left_files = {p.name for p in left.iterdir() if p.is_file()}
    right_files = {p.name for p in right.iterdir() if p.is_file()}
    only_left = left_files - right_files
    only_right = right_files - left_files
    for name in sorted(only_left):
        diffs.append(f"  only in fresh generation: {name}")
    for name in sorted(only_right):
        diffs.append(f"  only in committed tree:   {name}")
    common = sorted(left_files & right_files)
    for name in common:
        a, b = left / name, right / name
        if not filecmp.cmp(a, b, shallow=False):
            diffs.append(f"  drift: {name}")
            sample = list(difflib.unified_diff(
                b.read_text(encoding="utf-8").splitlines(),
                a.read_text(encoding="utf-8").splitlines(),
                fromfile=str(b),
                tofile=str(a),
                n=2,
                lineterm="",
            ))[:30]
            diffs.extend(f"    {line}" for line in sample)
    return diffs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate LinkML artifacts.")
    parser.add_argument(
        "--schema",
        type=Path,
        default=DEFAULT_SCHEMA,
        help="Path to the LinkML source schema.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUTDIR,
        help="Directory to write generated artifacts into.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Regenerate into a temp dir and diff against the committed "
            "artifacts.  Exits non-zero on drift."
        ),
    )
    args = parser.parse_args(argv)

    if not args.schema.exists():
        print(f"error: schema not found at {args.schema}", file=sys.stderr)
        return 2

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_dir = Path(tmp)
            regenerate(args.schema, tmp_dir)
            if not args.out_dir.exists():
                print(
                    f"error: committed output dir {args.out_dir} is missing; "
                    "run `make generate` first.",
                    file=sys.stderr,
                )
                return 1
            diffs = diff_dirs(tmp_dir, args.out_dir)
            if diffs:
                print("Ontology artifacts are stale; please run `make generate`:")
                for line in diffs:
                    print(line)
                return 1
            print("Ontology artifacts are up to date.")
            return 0

    # Normal regenerate mode.
    artifacts = regenerate(args.schema, args.out_dir)
    for name, path in artifacts.items():
        try:
            display = path.relative_to(PROJECT_ROOT)
        except ValueError:
            display = path
        print(f"wrote {name} -> {display}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
